### ISSUE TITLE
Update developer's guide

### ISSUE THREAD

**Issue by aakanksha-rai** [AY1920S2-CS2103T-W17-4/main#176]

**Comment by j-lum** [comment]
1 . intro
students (clarify)
remove nested bullet point

3.3.1
Facade with a small f.

3.3.2
Not so sure about the red arrow and the X on the arrow. Stick to known notation. If you are unclear about how to represent a relation, raise the issue with teaching staff (but not me).

3.3.3 
White isn't really good as a background color as it's not always clear.

3.3.6
Shouldn't this be in section 4 instead?

3.5.1 
done sessions isn't really grammatically sound.

Figure 24
No need for exceptions in activity diagrams, I've clarified this with prof.

Figure 26.
It is possible to replace the argument with a placeholder provided that you EXPLICITLY mention it in the paragraphs around the figure. 

4.1.5
pre-existing is grammatically incorrect.
A lot of code is not in code blocks.

Figure 27.
Missing info box on destroy markers.

Figure 28.
Missing info box on destroy markers.
Try not to curve the arrows if possible(?)


Figure 29.
Missing info box on destroy markers.

4.2
What is that even supposed to mean?
How is a user (((affiliated))) with functionalities?

4.4.2
Ta-tracker

4.3 
??????
In fact, what's a TSS?

4.3.1
If you contain 1 tss, then each tss refers to that one sad lonely tss.

Figure 35
Do the swimlanes really contribute to the diagram?

4.4.3.A1
If you can't find a decent alternative, don't bother thinking of a solution that obviously doesn't work. Even "syntax highlighting triggers upon pressing tab" or something would be ok but an infinite loop???

4.4.3.A2
I'm a huge UX enthusiast. But this is a document on software engineering decisions. 

4.7
mention this before the stuff that's not so important.

Figure 51.
UML diagram is somehow not styled properly or am I going blind?

AB. 
User stories for some stories are

AD.
Wrongly typed grammatical not is. 

AD5.
????

AD6.
Grammar/phrasing.

AD7.
Grammar/phrasing

AD9.
Are we being racist now?

Appendix
TSS is not defined so I wasn't going crazy when I couldn't understand what was going on.


Overall:
- Clarify with the prof on UML syntax instead of inventing stuff.
- Code belongs in codeblocks.
-  Poor grammar and phrasing. I couldn’t understand some parts.
- Define your abbreviations before using them.
- Missing alternatives in most implementation sections.
- Rearrange parts of your DG to make sure that important bits that you wrote stand out. 
- I’m worried for you guys.

Actionables:
I highly suggest that you guys take the time out, get together on a group call and have a group reading section where you read your DG/UG aloud to each other. Make sure the person reading is not the person who wrote it. 

Make sure UML formatting is consistent as well. 

There's a lot of mistakes in formatting, grammar, phrasing that really shouldn't exist by this point in time. Not to mention there's a lot of stuff that's required to be in there by the grading rubric that's still not written.

**Comment by aakanksha-rai** [comment]
Hey guys I just finished updating my part of the DG. I tried going through the whole thing. I made small changes here and there.

More changes needed that I didn't touch on:
- In section 3.4 (Model Component), it shows that Ta Tracker contains a UniqueStudentList and a UniqueGroupList which is untrue. It contains their
observable lists but not the list. 
- In section 4.4.1, the section of student component shouldn't be under alternative implementation. It should be before it and you should add an explanation on how it is structured. The next image could be stored under alternative implementation tho.
- In section 4.1.4 , you explain how delete student is different, add a sequence diagram and then explain it again in detail. Seems like overkill. Remove the initial explanation?
- Figure 31 looks pretty wrong. What are AddSessionCommand and AddSessionCommandParser doing here?
- You should add an explanation for figure 32
- In section 4.4.2, why has session done been explained again, this time in a different manner??
- Section 4.8 (filter command) should be before syntax highlighting. The S of student, session and C of claims should be in lower case.
- Diagram 51, activation bar for FilterStudentViewCommandParser is missing.
- I feel like the section on filter commands can be phrased in a better way.

Overall:
- Use ` not ' !!!!
- It is TaTrackerParser not TATrackerParser
- Lets try to finish our individual sections ASAP (say by Friday evening)
- Everyone should add some tests to the manual testing section in the appendix
- Look at the Effort section in the appendix and add more details
- Lets all get on a zoom call and read through the DG together slowly so that we can make the required changes (Friday night/Saturday morning).
